### PR TITLE
Add option to display popover without giving focus to this window

### PR DESCRIPTION
**Pull request by redbug26**

### CODE REVIEW

**Comment by sbooth** [comment]
This looks good.  I'm curious what the use case is for a popover that doesn't take keyboard focus- an inspector-type setup?

**Comment by redbug26** [comment]
sans titre 5
When I display the filter box. Without this option, the text field loose the focus :(

**Comment by sbooth** [comment]
What do you think about renaming `giveFocus` to `makeKey` to keep the terminology standard?

**Comment by redbug26** [comment]
It's your dev. No problem for me :) I've changed the source code

**Pull request merged**
